name: Docker Pull and Run

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/flask-sample:latest

      - name: Run Docker container
        run: docker run -p 8080:5000 ${{ secrets.DOCKERHUB_USERNAME }}/flask-sample:latest
