name: Docker Build, Push, and Run

on:
  push:
    branches:
      - master  # Adjust this to the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64  # Adjust the platforms as needed
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/flask-sample:latest

  run:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull Docker image
      run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/flask-sample:latest

    - name: Run Docker container
      run: docker run -d -p 5000:5000 --name flask-container ${{ secrets.DOCKERHUB_USERNAME }}/flask-sample:latest
